name       : perl-class-data-inheritable
version    : 0.08
release    : 4
source     :
    - http://search.cpan.org/CPAN/authors/id/T/TM/TMTM/Class-Data-Inheritable-0.08.tar.gz : 9967feceea15227e442ec818723163eb6d73b8947e31f16ab806f6e2391af14a
license    : GPL-1.0
summary    : Perl Class Data Inheritable Module
description: |
    Class::Data::Inheritable is for creating accessor/mutators to class data. That is, if you want to store something about your class as a whole (instead of about a single object). This data is then inherited by your subclasses and can be overriden.
component  : programming.perl
patterns   :
    - /usr/share/man/*
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
