name       : perl-class-data-inheritable
version    : '0.09'
release    : 10
source     :
    - https://cpan.metacpan.org/modules/by-module/Class/Class-Data-Inheritable-0.09.tar.gz : 44088d6e90712e187b8a5b050ca5b1c70efe2baa32ae123e9bd8f59f29f06e4d
license    : GPL-1.0
summary    : Perl Class Data Inheritable Module
description: |
    Class::Data::Inheritable is for creating accessor/mutators to class data. That is, if you want to store something about your class as a whole (instead of about a single object). This data is then inherited by your subclasses and can be overriden.
component  : programming.perl
patterns   :
    - /usr/share/man/*
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
